---
- name: setup bastion host profile
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import vpc setup variable
      include_vars: vars/output_vars
    
    - name: Import bastion setup variable
      include_vars: vars/bastion_setup

    - name: Create vprofile ec2-key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: save private key into bastion-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create SG for bastion Host\n
      ec2_group:
        name: bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionSG_out


    - name: Creating Bastion Host
      community.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        tags: 
          Name: "bastion-Host"
          Project: Vprofile
        exact_count: 1
        count_tag:
          Name: "bastion-Host"
          Project: Vprofile
        security_group: "{{bastionSG_out.group_id}}"
        subnet_id: "{{pubsub1id}}"
      register: bastionhost_out       

    